# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - rm -f bin/*
      - go build -o bin/courier cli/main.go

  lint:
    cmds:
      - golangci-lint run -v --new ./...

  test:
    cmds:
      - gotestsum --format testname

  test:cover:
    cmds:
      - go test -coverprofile=cover.out ./...
      - go tool cover -html=cover.out
